eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  cloud:
    openfeign:
      client:
        config:
          downstream2Next:
            url: http://downstream2-next:8081/hello
          downstream2Curr:
            url: http://downstream2-curr:8081/hello